### ISSUE TITLE
Class not found on case sensitive servers

### ISSUE THREAD

**Issue by Gnative** [GeneaLabs/laravel-sign-in-with-apple#10]
`Class 'GeneaLabs\LaravelSignInWithApple\Providers\SignInWithAppleProvider' not found ` 
error thrown on case sensitive server.

Class file name is SigninWithAppleProvider.php when it should be SignInWithAppleProvider.php
Capital **I** on SignIn. 

as referenced in the ServiceProvider.php 

```
 return $socialite
                    ->buildProvider(SignInWithAppleProvider::class, $config);
```

**Comment by mikebronner** [comment]
Thanks for the PR ... sorry it took so long. This should now be fixed in release 0.4.1.
