### ISSUE TITLE
Get firstName and lastName.

### ISSUE THREAD

**Issue by brjohnson4** [GeneaLabs/laravel-sign-in-with-apple#13]
Is there an easy way to pull in the user's first name and last name separately? I want to treat these as different fields in my app. Thanks!

**Comment by mikebronner** [comment]
@brjohnson4  Unfortunately, no. I have always done this as follows:
```php
$nameParts = explode(" ", $name);
$lastName = array_pop($nameParts);
$firstname = implode(" ", $nameParts);
```

**Comment by brjohnson4** [comment]
Thanks!
