### ISSUE TITLE
getUserByToken($token) results in error

### ISSUE THREAD

**Issue by adrian-schnell** [GeneaLabs/laravel-sign-in-with-apple#14]
Calling `Socialite::driver('sign-in-with-apple')->userFromToken($token);` results in an error:

> Argument 1 passed to GeneaLabs\\LaravelSignInWithApple\\Providers\\SignInWithAppleProvider::mapUserToObject() must be of the type array, null given, called in /var/www/vendor/laravel/socialite/src/Two/AbstractProvider.php on line 232

**Comment by mikebronner** [comment]
Hi @adrian-schnell, were you able to fix the issue?

**Comment by AgustinV08** [comment]
Error still pops up when using the userFromToken function

**Comment by mikebronner** [comment]
I don't believe `userFromToken` is supported in this package. See readme for implementation specifics:
```
$user = Socialite::driver("sign-in-with-apple")
            ->user();
```

**Comment by Skyquek** [comment]
Is there any workaround to get the function userFromToken() to work?
