### ISSUE TITLE
No email or name returned.

### ISSUE THREAD

**Issue by SDCCardsDeveloper** [GeneaLabs/laravel-sign-in-with-apple#15]
Hello,

Thanks for the great package.
I've done all the steps to work with Apple Sign-In but the result that returned have null name & email.

```
Laravel\Socialite\Two\User {#866 ▼
  +token: "ab37590f0496e4489b59b6c755f9b4c8d.0.msqsw.FQVbQXV-__jT3fqhkkatXQ"
  +refreshToken: "rf6bd2934e66147248597f58c1aa5e2e7.0.msqsw.Bu2vbPnEyLeib8bb1tNXrA"
  +expiresIn: 3600
  +id: "002026.9ebcbe224278487abc92c6f3f5c9b363.0247"
  +nickname: null
  +name: null
  +email: null
  +avatar: null
  +user: array:8 [▼
    "iss" => "https://appleid.apple.com"
    "aud" => "com.sdccards.service-id2"
    "exp" => 1585279148
    "iat" => 1585278548
    "sub" => "002026.9ebcbe224278487abc92c6f3f5c9b363.0247"
    "at_hash" => "yHuiSiPqGiPE-kkZ0Cc3jw"
    "auth_time" => 1585278546
    "nonce_supported" => true
  ]
}
```

I'm not sure if I missed something during the installation or the configuration of the package.
Any idea why this happens?
Thanks a lot

**Comment by mikebronner** [comment]
Hi @SDCCardsDeveloper, in my experience this has been due to some part of the configuration in the Apple Developer portal not being quite right. It could also be that the scopes are not configured properly.

**Comment by SDCCardsDeveloper** [comment]
Thanks, @mikebronner for your comment. 

The answer in this thread helps me solve this issue: https://stackoverflow.com/questions/57545635/cannot-get-name-email-with-sign-in-with-apple-on-real-device

Thanks again.

**Comment by mikebronner** [comment]
@SDCCardsDeveloper  Awesome, glad you solved it! I think my Socialiter package may have taken care of this for you? Not sure off the top of my head, it's been a while.
