### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by vonec** [GeneaLabs/laravel-sign-in-with-apple#18]
latest version does not support Laravel 6

**Comment by mikebronner** [comment]
@vonec sorry about that. I updated the reader to reflect that. It is a conscious decision to only support the current Laravel release. Please feel free to fork it and make any necessary code changes to make it run on the Laravel version you are using. Unfortunately I am unable to support anything other than the the latest version of Laravel.

**Comment by vonec** [comment]
ok let me form and modify it ...

**Comment by vonec** [comment]
can i edit and  use your video for demo?

**Comment by mikebronner** [comment]
You are free to use it as-is, but not if you edit it, sorry.

**Comment by fureszk** [comment]
"It is a conscious decision to only support the current Laravel release."

It is a conscious decision of many developers to use the latest **LTS** Laravel release.

**Comment by vonec** [comment]
https://socialiteproviders.netlify.app/providers/apple.html thank you

**Comment by himalayaahuja** [comment]
> @vonec sorry about that. I updated the reader to reflect that. It is a conscious decision to only support the current Laravel release. Please feel free to fork it and make any necessary code changes to make it run on the Laravel version you are using. Unfortunately I am unable to support anything other than the the latest version of Laravel.

"It is a conscious decision to only support the current Laravel release."

It is a conscious decision of many developers to use the **latest LTS Laravel release**.

**Comment by mikebronner** [comment]
@himalayaahuja  You're free to fork this package and change the dependencies and code to work with your app.
