### ISSUE TITLE
Using as a stateless provider

### ISSUE THREAD

**Issue by andreasbergqvist** [GeneaLabs/laravel-sign-in-with-apple#19]
Hi
We are building an mobile app and would like to use this provider with an Laravel backend.
But have a question.

For Facebook and Google we use:
`$socialiteUser = Socialite::driver('facebook')->stateless()->userFromToken($request->token);`
Where `$request->token` is the token sent from the app.

Both the Facebook and the Google provider now runs: `getUserByToken()` and does an request to verify the user. See:
https://github.com/laravel/socialite/blob/4.0/src/Two/GoogleProvider.php#L61

But in this provider the `getUserByToken()` function just decodes the token:
https://github.com/GeneaLabs/laravel-sign-in-with-apple/blob/1a2aabe7146ecd0dc7876e49d6891b29203649f7/src/Providers/SignInWithAppleProvider.php#L83

Wouldn't it be a good idea to be consistent with how the other providers work? Or is there something specific with Apple login that works different? Or could this provider still work but call some other function to verify the user?

I understand that this provider is build for the web implementation first but just wanted to raise the question!

Otherwise, great work!

**Comment by mikebronner** [comment]
Hi @andreasbergqvist, thanks for writing in! Apple doesn't work exactly like other OAuth providers. With SIWA you have to request a new token with each login, from what I remember, the token is not stored for reuse.

**Comment by pnlinh-it** [comment]
@andreasbergqvist 

Use can use this package: [SocialiteProviders/Apple](https://github.com/SocialiteProviders/Apple)

After login with apple on iOS device, your app will obtain the token, send this token to your server.

This token already has user information such as: email, name... You need to [verify this token](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/verifying_a_user) - this is already [implement by the package](https://github.com/SocialiteProviders/Apple/blob/master/Provider.php#L127).

**Comment by OrkhanAlikhanov** [comment]
There is a list of known [public keys from Apple](https://developer.apple.com/documentation/sign_in_with_apple/fetch_apple_s_public_key_for_verifying_token_signature) to do the job: https://appleid.apple.com/auth/keys
