### ISSUE TITLE
`Sign In With Apple` not returning user's name.

### ISSUE THREAD

**Issue by mikebronner** [GeneaLabs/laravel-sign-in-with-apple#2]
It seems the API is unstable, as at one point I was able to get both name and email, but now only get the email address.

**Comment by eqxDev** [comment]
Hi,

These seems like it is happening again?

**Comment by mikebronner** [comment]
Possibly. This would most likely be an issue with Apple.

**Comment by lattespirit** [comment]
@eqxDev @mikebronner 

Got the same issue.

`name` parameter is not included in `id_token` payload at the time of this writing.

So this line of code below always returns false

https://github.com/GeneaLabs/laravel-sign-in-with-apple/blob/867204f966c5052fab09df4a469b3dc8348ef368/src/Providers/SigninWithAppleProvider.php#L107

**Comment by poldixd** [comment]
> @eqxDev @mikebronner
> 
> Got the same issue.
> 
> `name` parameter is not included in `id_token` payload at the time of this writing.
> 
> So this line of code below always returns false
> 
> https://github.com/GeneaLabs/laravel-sign-in-with-apple/blob/867204f966c5052fab09df4a469b3dc8348ef368/src/Providers/SigninWithAppleProvider.php#L106-L107

Yes. Same error here. No name returned. 

I also removed the App on my Apple ID. After that I tried to login with your package. Still no name. When I dd() request()->user there is the name.
