### ISSUE TITLE
Error while getting user via access token

### ISSUE THREAD

**Issue by tberk** [GeneaLabs/laravel-sign-in-with-apple#25]
I successfully receive access token using firebase from my app but after sending it to my api server errors occur.

```php
$providedUser = Socialite::driver($driver)->stateless()->userFromToken($accessToken);
```

This code is working for google, facebook, linkedin but throws error for apple.

`[2020-08-18 11:55:32] production.ERROR: Argument 1 passed to GeneaLabs\LaravelSignInWithApple\Providers\SignInWithAppleProvider::mapUserToObject() must be of the type array, null given, called in /var/www/vhosts/******.com/vendor/laravel/socialite/src/Two/AbstractProvider.php on line 231 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to GeneaLabs\\LaravelSignInWithApple\\Providers\\SignInWithAppleProvider::mapUserToObject() must be of the type array, null given, called in /var/www/vhosts/******.com/vendor/laravel/socialite/src/Two/AbstractProvider.php on line 231 at /var/www/vhosts/******.com/vendor/genealabs/laravel-sign-in-with-apple/src/Providers/SignInWithAppleProvider.php:100)
[stacktrace]
#0 /var/www/vhosts/******.com/vendor/laravel/socialite/src/Two/AbstractProvider.php(231): GeneaLabs\\LaravelSignInWithApple\\Providers\\SignInWithAppleProvider->mapUserToObject()
#1 /var/www/vhosts/******.com/app/Http/Controllers/Api/App/AuthController.php(134): Laravel\\Socialite\\Two\\AbstractProvider->userFromToken()`

Edit: used idToken instead of access_token now it works.

**Comment by StarkLiew** [comment]
Wonder, why not return id_token instead of access_token? If id_token is return, then userFromToken() will not encounter mapUserToObject() error.

```
    public function user()
    {
        ...
        return $user
            ->setToken(Arr::get($response, 'access_token'))
            ->setRefreshToken(Arr::get($response, 'refresh_token'))
            ->setExpiresIn(Arr::get($response, 'expires_in'));
    }
```

**Comment by mikebronner** [comment]
@tberk Can you try release 0.4.4 and see if it works for you? Please let me know. :) Thanks!
