### ISSUE TITLE
Apple  is not redirect to url callback

### ISSUE THREAD

**Issue by fabioduarter** [GeneaLabs/laravel-sign-in-with-apple#29]
although the callback url is set correctly, after my login, apple redirect to my index and not to my callback route. Has anyone had this problem?

**Comment by mikebronner** [comment]
I haven't seen this issue. I've been using it daily in my most recent project and not seen that. If you could provide a test URL that would be great.

**Comment by fabioduarter** [comment]
of course: https://teste.eita.delivery

**Comment by fabioduarter** [comment]
Sorry friend, I managed to identify the problem. We still needed to add the callback route in excess of the csrf token. thank you very much and congratulations!
