### ISSUE TITLE
Why access_token instead of id_token?

### ISSUE THREAD

**Issue by StarkLiew** [GeneaLabs/laravel-sign-in-with-apple#30]
Wonder, why not return id_token instead access_token? If id_token is return, then userFromToken() will not encounter mapUserToObject() error.

```
    public function user()
    {
        ...
        return $user
            ->setToken(Arr::get($response, 'access_token'))
            ->setRefreshToken(Arr::get($response, 'refresh_token'))
            ->setExpiresIn(Arr::get($response, 'expires_in'));
    }
```

**Comment by mikebronner** [comment]
Hi @StarkLiew, thanks for providing more feedback on this. I will look into it.

Related to #25

**Comment by mikebronner** [comment]
@StarkLiew Can you try release 0.4.4 and see if it works for you? Please let me know. :) Thanks!

**Comment by StarkLiew** [comment]
@mikebronner Release 0.4.4 work like a charm... 💯  Thanks!

**Comment by StarkLiew** [comment]
> @StarkLiew Can you try release 0.4.4 and see if it works for you? Please let me know. :) Thanks!

@mikebronner Release 0.4.4 work like a charm... 💯 Thanks!
