### ISSUE TITLE
Laravel 7 support ?

### ISSUE THREAD

**Issue by ereznet** [GeneaLabs/laravel-sign-in-with-apple#31]
Laravel version: 7.28.4
PHP version: 7.4.10

# composer require genealabs/laravel-sign-in-with-apple
Using version ^0.5.0 for genealabs/laravel-sign-in-with-apple
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for genealabs/laravel-sign-in-with-apple ^0.5.0 -> satisfiable by genealabs/laravel-sign-in-with-apple[0.5.0].
    - Conclusion: remove laravel/framework v7.28.4
    - Conclusion: don't install laravel/framework v7.28.4
    - genealabs/laravel-sign-in-with-apple 0.5.0 requires illuminate/support ^8.0 -> satisfiable by laravel/framework[8.x-dev], illuminate/support[8.x-dev, v8.0.0, v8.0.1, v8.0.2, v8.0.3, v8.0.4, v8.1.0, v8.10.0, v8.2.0, v8.3.0, v8.4.0, v8.5.0, v8.6.0, v8.7.0, v8.7.1, v8.8.0, v8.9.0].
    - Can only install one of: laravel/framework[8.x-dev, v7.28.4].
    - don't install illuminate/support 8.x-dev|don't install laravel/framework v7.28.4
    - don't install illuminate/support v8.0.0|don't install laravel/framework v7.28.4
    - don't install illuminate/support v8.0.1|don't install laravel/framework v7.28.4
    - don't install illuminate/support v8.0.2|don't install laravel/framework v7.28.4
    - don't install illuminate/support v8.0.3|don't install laravel/framework v7.28.4
    - don't install illuminate/support v8.0.4|don't install laravel/framework v7.28.4
    - don't install illuminate/support v8.1.0|don't install laravel/framework v7.28.4
    - don't install illuminate/support v8.10.0|don't install laravel/framework v7.28.4
    - don't install illuminate/support v8.2.0|don't install laravel/framework v7.28.4
    - don't install illuminate/support v8.3.0|don't install laravel/framework v7.28.4
    - don't install illuminate/support v8.4.0|don't install laravel/framework v7.28.4
    - don't install illuminate/support v8.5.0|don't install laravel/framework v7.28.4
    - don't install illuminate/support v8.6.0|don't install laravel/framework v7.28.4
    - don't install illuminate/support v8.7.0|don't install laravel/framework v7.28.4
    - don't install illuminate/support v8.7.1|don't install laravel/framework v7.28.4
    - don't install illuminate/support v8.8.0|don't install laravel/framework v7.28.4
    - don't install illuminate/support v8.9.0|don't install laravel/framework v7.28.4
    - Installation request for laravel/framework (locked at v7.28.4, required as ^7.24) -> satisfiable by laravel/framework[v7.28.4].

Installation failed, reverting ./composer.json to its original content.

**Comment by mikebronner** [comment]
Hi @ereznet, sorry about that. I forgot to update the documentation, I went ahead and did that now. Only Laravel 8+ is currently supported.

**Comment by ereznet** [comment]
ErezNet

	
		#outlook a						{ padding:0; }
		body							{ direction: rtl; width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0; background: #fff; font-family: Arial; }

		.ExternalClass					{ width: 100%; }
		.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;}
		img								{ outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; }
		a img							{ border: none; }
		.image_fix						{ display: block; }
		p								{ margin: 1em 0; }
		h1, h2, h3, h4, h5, h6			{ color: black !important; }
		h1 a, h2 a, h3 a, h4 a, h5 a, h6 a { color: blue !important; }
		h1 a:active, h2 a:active,  h3 a:active, h4 a:active, h5 a:active, h6 a:active { color: red !important; }
		h1 a:visited, h2 a:visited,  h3 a:visited, h4 a:visited, h5 a:visited, h6 a:visited { color: purple !important; }
		table							{ border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; margin: 0; padding: 0; line-height: 100% !important; text-align: center; }
		table td						{ border-collapse: collapse; }
	



	
		
			 
		
	

	
		
			
				
					 
				
				
					
						לקוח יקר,
						החל מתאריך 23.11.17, במייל זה (support@ereznet.co.il) לא תינתן/תסופק תמיכה טכנית.
						אנו שמחים להציג בפניכם את מערכת ה-HelpDesk החדשה שלנו בכתובת:https://www.helpdesk.ereznet.co.il
						
							כל לקוחות ארזנט מתבקשים לבצע הרשמה למערכת בכתובת: https://www.helpdesk.ereznet.co.il/registerההרשמה בחינם, אך חשוב לזכור שעלייכם לבצע הרשמה בעזרת הכתובת דואר שעמה ביצעתם את הזמנתכם!
						
						במערכת HelpDesk ניתן למצוא מגוון רחב של פעולות:
						
							להקים/לפתוח קריאה לשירות במגוון קטגוריות.
							הקמת כרטיס מתבצעת מתוך אתרנו, כך שבמידה ותיבת הדואר שלכם לא פעילה עדיין תוכלו לשלוח פניות.
							צפייה בהסטוריית הכרטיסים שלי.
							מעקב לכרטיס, ושינוי סטטוס.
							אפשרות להוספת מידע פנימי לכרטיס: כגון סיסמאות רגישות וכתובת IP והכל בסביבה מאובטחת (SSL).
							אפשרות לעדכון כרטיס ישירות מתוך תיבת הדואר שלכם, בעזרת שליחת מייל חוזר.
							בנוסף למערכת הכרטיסים, תמצאו מאגר מידע אשר נעדכן עבור הודעות חשובות בחברתנו.
							ועוד מגוון אפשרויות אשר יפיקו תמיכה ושליטה טובה יותר לקהל לקוחותינו.
						
						נשמח לעמוד לשירותכם :)
					
				
				
					 
				
				
					
						בברכה,צוות ארזנט - פתרונות אינטרנטמחלקת תמיכה טכניתטלפון משרד: 077-2148004 | פקס: 077-2148005כתובת אתרינו: https://www.ErezNet.co.il

**Comment by vesper8** [comment]
First I installed 0.5.0 and got the error because it doesn't support Laravel 7. Then I tried to install 0.4.4 and got an error because it doesn't support Socialite 5 (which I am already using, which does support Laravel 7)

So then I just forked it and changed `"illuminate/support": "^8.0",` to `"illuminate/support": "^7.0|^8.0",`

And then it installed correctly and seems to be working just fine

My 2 cents, if you're going to require that your package uses Socialite 5, and Socialite 5 supports Laravel 7 & 8, then your package should too

Thanks for the package

**Comment by ereznet** [comment]
ErezNet

	
		#outlook a						{ padding:0; }
		body							{ direction: rtl; width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0; background: #fff; font-family: Arial; }

		.ExternalClass					{ width: 100%; }
		.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;}
		img								{ outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; }
		a img							{ border: none; }
		.image_fix						{ display: block; }
		p								{ margin: 1em 0; }
		h1, h2, h3, h4, h5, h6			{ color: black !important; }
		h1 a, h2 a, h3 a, h4 a, h5 a, h6 a { color: blue !important; }
		h1 a:active, h2 a:active,  h3 a:active, h4 a:active, h5 a:active, h6 a:active { color: red !important; }
		h1 a:visited, h2 a:visited,  h3 a:visited, h4 a:visited, h5 a:visited, h6 a:visited { color: purple !important; }
		table							{ border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; margin: 0; padding: 0; line-height: 100% !important; text-align: center; }
		table td						{ border-collapse: collapse; }
	



	
		
			 
		
	

	
		
			
				
					 
				
				
					
						לקוח יקר,
						החל מתאריך 23.11.17, במייל זה (support@ereznet.co.il) לא תינתן/תסופק תמיכה טכנית.
						אנו שמחים להציג בפניכם את מערכת ה-HelpDesk החדשה שלנו בכתובת:https://www.helpdesk.ereznet.co.il
						
							כל לקוחות ארזנט מתבקשים לבצע הרשמה למערכת בכתובת: https://www.helpdesk.ereznet.co.il/registerההרשמה בחינם, אך חשוב לזכור שעלייכם לבצע הרשמה בעזרת הכתובת דואר שעמה ביצעתם את הזמנתכם!
						
						במערכת HelpDesk ניתן למצוא מגוון רחב של פעולות:
						
							להקים/לפתוח קריאה לשירות במגוון קטגוריות.
							הקמת כרטיס מתבצעת מתוך אתרנו, כך שבמידה ותיבת הדואר שלכם לא פעילה עדיין תוכלו לשלוח פניות.
							צפייה בהסטוריית הכרטיסים שלי.
							מעקב לכרטיס, ושינוי סטטוס.
							אפשרות להוספת מידע פנימי לכרטיס: כגון סיסמאות רגישות וכתובת IP והכל בסביבה מאובטחת (SSL).
							אפשרות לעדכון כרטיס ישירות מתוך תיבת הדואר שלכם, בעזרת שליחת מייל חוזר.
							בנוסף למערכת הכרטיסים, תמצאו מאגר מידע אשר נעדכן עבור הודעות חשובות בחברתנו.
							ועוד מגוון אפשרויות אשר יפיקו תמיכה ושליטה טובה יותר לקהל לקוחותינו.
						
						נשמח לעמוד לשירותכם :)
					
				
				
					 
				
				
					
						בברכה,צוות ארזנט - פתרונות אינטרנטמחלקת תמיכה טכניתטלפון משרד: 077-2148004 | פקס: 077-2148005כתובת אתרינו: https://www.ErezNet.co.il
