### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by abdulmanan7** [GeneaLabs/laravel-sign-in-with-apple#33]
Problem 1
    - Root composer.json requires genealabs/laravel-sign-in-with-apple ^0.5.0 -> satisfiable by genealabs/laravel-sign-in-with-apple[0.5.0].
    - genealabs/laravel-sign-in-with-apple 0.5.0 requires illuminate/support ^8.0 -> found illuminate/support[v8.0.0, ..., v8.26.1] but these were not loaded, likely because it conflicts with another require.

**Comment by mikebronner** [comment]
hi @abdulmanan7, it appears you have a versioning conflict with your packages. This does not appear to be caused by this package. Make sure you are on Laravel 8.x, and this package will install.

**Comment by hatimhussein** [comment]
use custom version of this package (0.4.3))

composer require genealabs/laravel-sign-in-with-apple "0.4.3"
