### ISSUE TITLE
Add your package to the list of socialite providers

### ISSUE THREAD

**Issue by Fluxlicious** [GeneaLabs/laravel-sign-in-with-apple#8]
There's a nice list of all Socialite providers, might be usefull if your package was listed.
See https://socialiteproviders.netlify.com/contribute.html

**Comment by mikebronner** [comment]
@Fluxlicious Thanks for the suggestion. :)

**Comment by vonec** [comment]
why do we need ruby :-/ cant we do that as a  scheduled job on laravel? also please add to socialite providers :)

**Comment by mikebronner** [comment]
Hi @vonec, Ruby was the easiest way for me to create a JWT token for the Apple services. If you know another way, feel free to use that. It is not needed for the app, only for the configuration process.

**Comment by mikebronner** [comment]
@Fluxlicious @vonec Unfortunately this package is not compatible with how the Sociality Providers repo works as it is using customized functionality that they can't support.

**Comment by alinmiron** [comment]
> why do we need ruby :-/ cant we do that as a scheduled job on laravel? also please add to socialite providers :)

maybe this can help: https://github.com/laravel/socialite/issues/369#issuecomment-539014190
