### ISSUE TITLE
Response error from Apple invalid_client

### ISSUE THREAD

**Issue by shiloanton** [GeneaLabs/laravel-sign-in-with-apple#9]
Hi, after rediretion to callback method, got this error:
"Client error: `POST https://appleid.apple.com/auth/token` resulted in a `400 Bad Request` response:\n{\"error\":\"invalid_client\"}\n"

**Comment by shiloanton** [comment]
The problem was that I installed an expiration for more than six months.

**Comment by mikebronner** [comment]
Glad to hear you solved it. :)
